export const TARGET_FILES = [
  {
    groupId: 'alacritty',
    name: 'alacritty config',
    path: ['~/.config/alacritty/alacritty.toml', '~/.alacritty.toml'],
    isDirectory: false,
  },
  {
    groupId: 'aws',
    name: 'config',
    path: '~/.aws/config',
    isDirectory: false,
  },
  {
    groupId: 'aws',
    name: 'credentials',
    path: '~/.aws/credentials',
    isDirectory: false,
  },
  {
    groupId: 'bash',
    name: '.bashrc',
    path: '~/.bashrc',
    isDirectory: false,
  },
  {
    groupId: 'bash',
    name: '.bash_profile',
    path: '~/.bash_profile',
    isDirectory: false,
  },
  {
    groupId: 'bash',
    name: '.profile',
    path: '~/.profile',
    isDirectory: false,
  },
  {
    groupId: 'bash',
    name: '.inputrc',
    path: '~/.inputrc',
    isDirectory: false,
  },
  {
    groupId: 'cargo',
    name: 'config.toml',
    path: '~/.cargo/config.toml',
    isDirectory: false,
  },
  {
    groupId: 'claude',
    name: 'settings.json',
    path: '~/.claude/settings.json',
    isDirectory: false,
  },
  {
    groupId: 'claude',
    name: 'commands',
    path: '~/.claude/commands/',
    isDirectory: true,
  },
  {
    groupId: 'claude',
    name: 'skills',
    path: '~/.claude/skills/',
    isDirectory: true,
  },
  {
    groupId: 'claude',
    name: 'agents',
    path: '~/.claude/agents/',
    isDirectory: true,
  },
  {
    groupId: 'claude',
    name: 'CLAUDE.md',
    path: '~/.claude/CLAUDE.md',
    isDirectory: false,
  },
  {
    groupId: 'claude',
    name: 'legacy config dir',
    path: '~/.config/claude/',
    isDirectory: true,
  },
  {
    groupId: 'cursor',
    name: 'settings.json',
    path: '~/Library/Application Support/Cursor/User/settings.json',
    isDirectory: false,
  },
  {
    groupId: 'cursor',
    name: 'keybindings.json',
    path: '~/Library/Application Support/Cursor/User/keybindings.json',
    isDirectory: false,
  },
  {
    groupId: 'cursor',
    name: 'snippets',
    path: '~/Library/Application Support/Cursor/User/snippets/',
    isDirectory: true,
  },
  {
    groupId: 'docker',
    name: 'config.json',
    path: '~/.docker/config.json',
    isDirectory: false,
  },
  {
    groupId: 'emacs',
    name: '.emacs',
    path: '~/.emacs',
    isDirectory: false,
  },
  {
    groupId: 'emacs',
    name: '.emacs.d',
    path: '~/.emacs.d/',
    isDirectory: true,
  },
  {
    groupId: 'fish',
    name: 'config.fish',
    path: '~/.config/fish/config.fish',
    isDirectory: false,
  },
  {
    groupId: 'git',
    name: 'config.yml',
    path: '~/.config/gh/config.yml',
    isDirectory: false,
  },
  {
    groupId: 'git',
    name: 'hosts.yml',
    path: '~/.config/gh/hosts.yml',
    isDirectory: false,
  },
  {
    groupId: 'ghostty',
    name: 'ghostty config',
    path: [
      '~/.config/ghostty/config.ghostty',
      '~/.config/ghostty/config',
      '~/Library/Application Support/com.mitchellh.ghostty/config.ghostty',
      '~/Library/Application Support/com.mitchellh.ghostty/config',
    ],
    isDirectory: false,
  },
  {
    groupId: 'git',
    name: '.gitconfig',
    path: '~/.gitconfig',
    isDirectory: false,
  },
  {
    groupId: 'git',
    name: '.gitignore_global',
    path: '~/.gitignore_global',
    isDirectory: false,
  },
  {
    groupId: 'git',
    name: 'git config',
    path: '~/.config/git/config',
    isDirectory: false,
  },
  {
    groupId: 'helix',
    name: 'config.toml',
    path: '~/.config/helix/config.toml',
    isDirectory: false,
  },
  {
    groupId: 'helix',
    name: 'languages.toml',
    path: '~/.config/helix/languages.toml',
    isDirectory: false,
  },
  {
    groupId: 'jetbrains',
    name: 'JetBrains options',
    path: '~/Library/Application Support/JetBrains/',
    isDirectory: true,
  },
  {
    groupId: 'k9s',
    name: 'config.yaml',
    path: [
      '~/Library/Application Support/k9s/config.yaml',
      '~/.config/k9s/config.yaml',
    ],
    isDirectory: false,
  },
  {
    groupId: 'kube',
    name: 'config',
    path: '~/.kube/config',
    isDirectory: false,
  },
  {
    groupId: 'lazygit',
    name: 'config.yml',
    path: [
      '~/Library/Application Support/lazygit/config.yml',
      '~/.config/lazygit/config.yml',
    ],
    isDirectory: false,
  },
  {
    groupId: 'mise',
    name: 'config.toml',
    path: ['~/.config/mise/config.toml', '~/.mise/config.toml'],
    isDirectory: false,
  },
  {
    groupId: 'neovim',
    name: 'nvim config',
    path: '~/.config/nvim/',
    isDirectory: true,
  },
  {
    groupId: 'npm',
    name: '.npmrc',
    path: '~/.npmrc',
    isDirectory: false,
  },
  {
    groupId: 'nushell',
    name: 'config.nu',
    path: [
      '~/Library/Application Support/nushell/config.nu',
      '~/.config/nushell/config.nu',
    ],
    isDirectory: false,
  },
  {
    groupId: 'nushell',
    name: 'env.nu',
    path: [
      '~/Library/Application Support/nushell/env.nu',
      '~/.config/nushell/env.nu',
    ],
    isDirectory: false,
  },
  {
    groupId: 'nushell',
    name: 'login.nu',
    path: [
      '~/Library/Application Support/nushell/login.nu',
      '~/.config/nushell/login.nu',
    ],
    isDirectory: false,
  },
  {
    groupId: 'opencode',
    name: 'opencode.json',
    path: '~/.config/opencode/opencode.json',
    isDirectory: false,
  },
  {
    groupId: 'opencode',
    name: 'commands',
    path: '~/.config/opencode/commands/',
    isDirectory: true,
  },
  {
    groupId: 'opencode',
    name: 'skills',
    path: '~/.config/opencode/skills/',
    isDirectory: true,
  },
  {
    groupId: 'opencode',
    name: 'agents',
    path: '~/.config/opencode/agents/',
    isDirectory: true,
  },
  {
    groupId: 'opencode',
    name: 'plugins',
    path: '~/.config/opencode/plugins/',
    isDirectory: true,
  },
  {
    groupId: 'opencode',
    name: 'themes',
    path: '~/.config/opencode/themes/',
    isDirectory: true,
  },
  {
    groupId: 'opencode',
    name: 'legacy project config dir',
    path: '~/.opencode/',
    isDirectory: true,
  },
  {
    groupId: 'poetry',
    name: 'config.toml',
    path: [
      '~/Library/Application Support/pypoetry/config.toml',
      '~/.config/pypoetry/config.toml',
    ],
    isDirectory: false,
  },
  {
    groupId: 'pyenv',
    name: '.pyenv',
    path: '~/.pyenv/',
    isDirectory: true,
  },
  {
    groupId: 'ripgrep',
    name: '.ripgreprc',
    path: '~/.ripgreprc',
    isDirectory: false,
  },
  {
    groupId: 'ssh',
    name: 'config',
    path: '~/.ssh/config',
    isDirectory: false,
  },
  {
    groupId: 'starship',
    name: 'starship.toml',
    path: '~/.config/starship.toml',
    isDirectory: false,
  },
  {
    groupId: 'terraform',
    name: 'terraform rc',
    path: ['~/.terraformrc', '~/.config/terraform.rc'],
    isDirectory: false,
  },
  {
    groupId: 'tmux',
    name: '.tmux.conf',
    path: '~/.tmux.conf',
    isDirectory: false,
  },
  {
    groupId: 'tmux',
    name: 'tmux config',
    path: '~/.config/tmux/tmux.conf',
    isDirectory: false,
  },
  {
    groupId: 'tool-versions',
    name: '.tool-versions',
    path: '~/.tool-versions',
    isDirectory: false,
  },
  {
    groupId: 'vim',
    name: '.vimrc',
    path: '~/.vimrc',
    isDirectory: false,
  },
  {
    groupId: 'vim',
    name: '.vim',
    path: '~/.vim/',
    isDirectory: true,
  },
  {
    groupId: 'vscode',
    name: 'settings.json',
    path: '~/Library/Application Support/Code/User/settings.json',
    isDirectory: false,
  },
  {
    groupId: 'vscode',
    name: 'keybindings.json',
    path: '~/Library/Application Support/Code/User/keybindings.json',
    isDirectory: false,
  },
  {
    groupId: 'vscode',
    name: 'snippets',
    path: '~/Library/Application Support/Code/User/snippets/',
    isDirectory: true,
  },
  {
    groupId: 'vscodium',
    name: 'settings.json',
    path: '~/Library/Application Support/VSCodium/User/settings.json',
    isDirectory: false,
  },
  {
    groupId: 'vscodium',
    name: 'keybindings.json',
    path: '~/Library/Application Support/VSCodium/User/keybindings.json',
    isDirectory: false,
  },
  {
    groupId: 'warp',
    name: 'warp config dir',
    path: '~/.warp/',
    isDirectory: true,
  },
  {
    groupId: 'wezterm',
    name: 'wezterm config',
    path: ['~/.wezterm.lua', '~/.config/wezterm/wezterm.lua'],
    isDirectory: false,
  },
  {
    groupId: 'windsurf',
    name: 'settings.json',
    path: '~/Library/Application Support/Windsurf/User/settings.json',
    isDirectory: false,
  },
  {
    groupId: 'windsurf',
    name: 'keybindings.json',
    path: '~/Library/Application Support/Windsurf/User/keybindings.json',
    isDirectory: false,
  },
  {
    groupId: 'windsurf',
    name: 'snippets',
    path: '~/Library/Application Support/Windsurf/User/snippets/',
    isDirectory: true,
  },
  {
    groupId: 'yarn',
    name: '.yarnrc',
    path: '~/.yarnrc',
    isDirectory: false,
  },
  {
    groupId: 'yarn',
    name: '.yarnrc.yml',
    path: '~/.yarnrc.yml',
    isDirectory: false,
  },
  {
    groupId: 'zed',
    name: 'settings.json',
    path: '~/.config/zed/settings.json',
    isDirectory: false,
  },
  {
    groupId: 'zed',
    name: 'keymap.json',
    path: '~/.config/zed/keymap.json',
    isDirectory: false,
  },
  {
    groupId: 'zed',
    name: 'tasks.json',
    path: '~/.config/zed/tasks.json',
    isDirectory: false,
  },
  {
    groupId: 'zellij',
    name: 'config.kdl',
    path: '~/.config/zellij/config.kdl',
    isDirectory: false,
  },
  {
    groupId: 'zsh',
    name: '.zshrc',
    path: '~/.zshrc',
    isDirectory: false,
  },
  {
    groupId: 'zsh',
    name: '.zprofile',
    path: '~/.zprofile',
    isDirectory: false,
  },
  {
    groupId: 'zsh',
    name: '.zshenv',
    path: '~/.zshenv',
    isDirectory: false,
  },
  {
    groupId: 'zsh',
    name: '.zlogin',
    path: '~/.zlogin',
    isDirectory: false,
  },
  {
    groupId: 'zsh',
    name: '.zlogout',
    path: '~/.zlogout',
    isDirectory: false,
  },
  {
    groupId: 'zsh',
    name: 'zsh config dir',
    path: '~/.config/zsh/',
    isDirectory: true,
  },
  {
    groupId: 'openclaw',
    name: 'openclaw.json',
    path: '~/.openclaw/openclaw.json',
    isDirectory: false,
  },
  {
    groupId: 'openclaw',
    name: 'workspace',
    path: '~/.openclaw/workspace',
    isDirectory: true,
  },
  {
    groupId: 'openclaw',
    name: 'credentials',
    path: '~/.openclaw/credentials',
    isDirectory: true,
  },
];
